#! /bin/sh

### BEGIN INIT INFO
# Provides:		capture-wifi-data
# Required-Start:	$local_fs $remote_fs
# Required-Stop:	$local_fs $remote_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Capture wifi data.
### END INIT INFO

set -e


case "$1" in
  start)
	cd /root/wifi_data
	/usr/bin/python capture_wifi_data.py
        ;;
  stop)
        pkill airodump-ng
        ;;
  *)
        exit 1
        ;;

esac

exit 0
